### ISSUE TITLE
 im trying to contact you to see if you want to contrib

### ISSUE THREAD

**Issue by tailscreatesstuff32** [a740g/raylib-Nuget#1]
i see you faved my fbquake 2 work in progress i really need collabs

i added you as collab let me know if your intertested

**Comment by a740g** [comment]
Hey, I saw your collab request and actually wanted to reach out to you to discuss.
I starred fbquake 2 because it is an interesting project. However, I am kind of deeply involved with QB64-PE among other things at the moment and rarely have time to do anything else. I can accept your invite, but I cannot promise I'll be able to contribute anytime soon. If that is ok, I'll accept else I'll just let it time-out.

**Comment by tailscreatesstuff32** [comment]
yeah u can accept it :)
more help the better
